server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: asura-restful
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
    serialization:
      write-dates-as-timestamps: false

knife4j:
  enable: true
  setting:
    language: zh_cn
  cors:
    enable: true

logging:
  level:
    org.asura.restful: DEBUG