<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <!-- https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-starter-parent -->
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.5.13</version>
    </parent>

    <groupId>io.github.limengcanyu</groupId>
    <artifactId>limengcanyu-boot</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <packaging>pom</packaging>

    <modules>
        <module>${project.artifact.name}-activiti</module>
        <module>${project.artifact.name}-actuator</module>
        <module>${project.artifact.name}-admin-client</module>
        <module>${project.artifact.name}-admin-server</module>
        <module>${project.artifact.name}-akka</module>
        <module>${project.artifact.name}-aliyun</module>
        <module>${project.artifact.name}-annotation</module>
        <module>${project.artifact.name}-aop</module>
        <module>${project.artifact.name}-arthas</module>
        <module>${project.artifact.name}-async</module>
        <module>${project.artifact.name}-auto-configuration</module>
        <module>${project.artifact.name}-batch</module>
        <module>${project.artifact.name}-caffeine</module>
        <module>${project.artifact.name}-camunda</module>
        <module>${project.artifact.name}-clickhouse</module>
        <module>${project.artifact.name}-common</module>
        <module>${project.artifact.name}-configuration-processor</module>
        <module>${project.artifact.name}-couchbase</module>
        <module>${project.artifact.name}-custom-starter</module>
        <module>${project.artifact.name}-custom-starter-test</module>
        <module>${project.artifact.name}-cassandra</module>
        <module>${project.artifact.name}-elasticsearch</module>
        <module>${project.artifact.name}-graphql</module>
        <module>${project.artifact.name}-jdbc</module>
        <module>${project.artifact.name}-jooq</module>
        <module>${project.artifact.name}-jpa</module>
        <module>${project.artifact.name}-liteflow</module>
        <module>${project.artifact.name}-mongodb</module>
        <module>${project.artifact.name}-neo4j</module>
        <module>${project.artifact.name}-pulsar</module>
        <module>${project.artifact.name}-quartz</module>
        <module>${project.artifact.name}-r2dbc</module>
        <module>${project.artifact.name}-rabbitmq</module>
        <module>${project.artifact.name}-redis</module>
        <module>${project.artifact.name}-redisson</module>
        <module>${project.artifact.name}-redisson-client</module>
        <module>${project.artifact.name}-redisson-interface</module>
        <module>${project.artifact.name}-redisson-server</module>
        <module>${project.artifact.name}-disruptor</module>
        <module>${project.artifact.name}-docker</module>
        <module>${project.artifact.name}-doris</module>
        <module>${project.artifact.name}-example</module>
        <module>${project.artifact.name}-fastexcel</module>
        <module>${project.artifact.name}-flaw</module>
        <module>${project.artifact.name}-flowable</module>
        <module>spring-boot-graphql</module>
        <module>${project.artifact.name}-graphql-java-kickstart</module>
        <module>${project.artifact.name}-guava</module>
        <module>${project.artifact.name}-hazelcast</module>
        <module>${project.artifact.name}-httpcomponents</module>
        <module>${project.artifact.name}-hystrix</module>
        <module>${project.artifact.name}-i18n</module>
        <module>${project.artifact.name}-influxdb</module>
        <module>${project.artifact.name}-jar-war</module>
        <module>${project.artifact.name}-jetty</module>
        <module>${project.artifact.name}-jib</module>
        <module>${project.artifact.name}-jkube</module>
        <module>spring-boot-jpa</module>
        <module>${project.artifact.name}-json</module>
        <module>${project.artifact.name}-jwt</module>
        <module>${project.artifact.name}-kafka</module>
        <module>${project.artifact.name}-kafka-streams</module>
        <module>${project.artifact.name}-knife4j</module>
        <module>${project.artifact.name}-kubernetes</module>
        <module>${project.artifact.name}-log</module>
        <module>${project.artifact.name}-logstash</module>
        <module>${project.artifact.name}-mongo</module>
        <module>${project.artifact.name}-multi-datasource-transaction</module>
        <module>${project.artifact.name}-mybatis-plus</module>
        <module>spring-boot-mybatis-plus-basic</module>
        <module>spring-boot-mybatisplus</module>
        <module>${project.artifact.name}-mybatis-plus-druid-dynamic-datasource</module>
        <module>${project.artifact.name}-mybatis-plus-druid-multi-datasource</module>
        <module>${project.artifact.name}-mybatis-plus-sharding-jdbc</module>
        <module>${project.artifact.name}-nebula</module>
        <module>${project.artifact.name}-netty</module>
        <module>${project.artifact.name}-netty-client</module>
        <module>${project.artifact.name}-netty-common</module>
        <module>${project.artifact.name}-netty-server</module>
        <module>${project.artifact.name}-okhttp</module>
        <module>${project.artifact.name}-poi</module>
        <module>${project.artifact.name}-postgressql</module>
        <module>${project.artifact.name}-prometheus</module>
        <module>spring-boot-pulsar</module>
        <module>spring-boot-quartz</module>
        <module>${project.artifact.name}-questdb</module>
        <module>spring-boot-rabbitmq</module>
        <module>${project.artifact.name}-rabbitmq-consumer</module>
        <module>${project.artifact.name}-rabbitmq-producer</module>
        <module>${project.artifact.name}-rate-limit</module>
        <module>spring-boot-redis</module>
        <module>${project.artifact.name}-redis-jedis</module>
        <module>${project.artifact.name}-redis-reactive</module>
        <module>spring-boot-redis-redisson</module>
        <module>spring-boot-redisson</module>
        <module>${project.artifact.name}-resilience4j</module>
        <module>${project.artifact.name}-rocketmq</module>
        <module>${project.artifact.name}-rocketmq-consumer</module>
        <module>${project.artifact.name}-rocketmq-example</module>
        <module>${project.artifact.name}-rocketmq-producer</module>
        <module>${project.artifact.name}-screw</module>
        <module>${project.artifact.name}-security</module>
        <module>${project.artifact.name}-sentinel</module>
        <module>${project.artifact.name}-shardingsphere</module>
        <module>${project.artifact.name}-shardingsphere-jdbc</module>
        <module>${project.artifact.name}-skywalking</module>
        <module>${project.artifact.name}-ssl</module>
        <module>${project.artifact.name}-rest-template</module>
        <module>${project.artifact.name}-temporal</module>
        <module>${project.artifact.name}-test</module>
        <module>${project.artifact.name}-thrift</module>
        <module>${project.artifact.name}-tomcat</module>
        <module>${project.artifact.name}-tree</module>
        <module>${project.artifact.name}-undertow</module>
        <module>${project.artifact.name}-validation</module>
        <module>${project.artifact.name}-webflux</module>
        <module>${project.artifact.name}-xxl-job</module>
    </modules>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <java.version>25</java.version>
        <!-- 定义变量 -->
        <project.artifact.name>limengcanyu</project.artifact.name>
    </properties>

    <dependencyManagement>
        <dependencies>
            <!-- Source: https://mvnrepository.com/artifact/de.codecentric/spring-boot-admin-dependencies -->
            <dependency>
                <groupId>de.codecentric</groupId>
                <artifactId>spring-boot-admin-dependencies</artifactId>
                <version>3.2.3</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <!-- Source: https://mvnrepository.com/artifact/org.testcontainers/testcontainers-bom -->
            <dependency>
                <groupId>org.testcontainers</groupId>
                <artifactId>testcontainers-bom</artifactId>
                <version>2.0.5</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <!-- Source: https://mvnrepository.com/artifact/me.ahoo.cosid/cosid-spring-boot-starter -->
            <dependency>
                <groupId>me.ahoo.cosid</groupId>
                <artifactId>cosid-spring-boot-starter</artifactId>
                <version>3.0.5</version>
                <scope>compile</scope>
            </dependency>

            <!-- Source: https://mvnrepository.com/artifact/org.redisson/redisson-spring-boot-starter -->
            <dependency>
                <groupId>org.redisson</groupId>
                <artifactId>redisson-spring-boot-starter</artifactId>
                <version>4.3.1</version>
                <scope>compile</scope>
            </dependency>

            <!-- Source: https://mvnrepository.com/artifact/org.apache.commons/commons-pool2 -->
            <dependency>
                <groupId>org.apache.commons</groupId>
                <artifactId>commons-pool2</artifactId>
                <version>2.13.1</version>
                <scope>compile</scope>
            </dependency>

            <!-- Source: https://mvnrepository.com/artifact/com.yomahub/tlog-all-spring-boot-starter -->
            <dependency>
                <groupId>com.yomahub</groupId>
                <artifactId>tlog-all-spring-boot-starter</artifactId>
                <version>1.5.2</version>
                <scope>compile</scope>
            </dependency>

            <!-- Source: https://mvnrepository.com/artifact/com.alibaba/easyexcel -->
            <dependency>
                <groupId>com.alibaba</groupId>
                <artifactId>easyexcel</artifactId>
                <version>4.0.3</version>
                <scope>compile</scope>
            </dependency>

            <!-- Source: https://mvnrepository.com/artifact/com.alibaba.cloud/spring-cloud-starter-alibaba-sentinel -->
            <dependency>
                <groupId>com.alibaba.cloud</groupId>
                <artifactId>spring-cloud-starter-alibaba-sentinel</artifactId>
                <version>2025.1.0.0</version>
                <scope>compile</scope>
            </dependency>

            <!-- Source: https://mvnrepository.com/artifact/com.baomidou/mybatis-plus-spring-boot3-starter -->
            <dependency>
                <groupId>com.baomidou</groupId>
                <artifactId>mybatis-plus-spring-boot3-starter</artifactId>
                <version>3.5.16</version>
                <scope>compile</scope>
            </dependency>

            <!-- Source: https://mvnrepository.com/artifact/com.baomidou/mybatis-plus-extension -->
            <dependency>
                <groupId>com.baomidou</groupId>
                <artifactId>mybatis-plus-extension</artifactId>
                <version>3.5.16</version>
                <scope>compile</scope>
            </dependency>

            <!-- Source: https://mvnrepository.com/artifact/com.baomidou/mybatis-plus-annotation -->
            <dependency>
                <groupId>com.baomidou</groupId>
                <artifactId>mybatis-plus-annotation</artifactId>
                <version>3.5.16</version>
                <scope>compile</scope>
            </dependency>

            <!-- Source: https://mvnrepository.com/artifact/com.baomidou/mybatis-plus-jsqlparser -->
            <dependency>
                <groupId>com.baomidou</groupId>
                <artifactId>mybatis-plus-jsqlparser</artifactId>
                <version>3.5.16</version>
                <scope>compile</scope>
            </dependency>

            <!-- Source: https://mvnrepository.com/artifact/com.baomidou/mybatis-plus-generator -->
            <dependency>
                <groupId>com.baomidou</groupId>
                <artifactId>mybatis-plus-generator</artifactId>
                <version>3.5.16</version>
                <scope>compile</scope>
            </dependency>

            <!-- Source: https://mvnrepository.com/artifact/com.baomidou/mybatis-plus-spring-boot3-starter-test -->
            <dependency>
                <groupId>com.baomidou</groupId>
                <artifactId>mybatis-plus-spring-boot3-starter-test</artifactId>
                <version>3.5.16</version>
                <scope>test</scope>
            </dependency>

            <!-- Source: https://mvnrepository.com/artifact/com.github.yulichang/mybatis-plus-join-boot-starter -->
            <dependency>
                <groupId>com.github.yulichang</groupId>
                <artifactId>mybatis-plus-join-boot-starter</artifactId>
                <version>1.5.7</version>
                <scope>compile</scope>
            </dependency>

            <!-- Source: https://mvnrepository.com/artifact/org.freemarker/freemarker -->
            <dependency>
                <groupId>org.freemarker</groupId>
                <artifactId>freemarker</artifactId>
                <version>2.3.34</version>
                <scope>compile</scope>
            </dependency>

            <!-- Source: https://mvnrepository.com/artifact/com.mysql/mysql-connector-j -->
            <dependency>
                <groupId>com.mysql</groupId>
                <artifactId>mysql-connector-j</artifactId>
                <version>9.7.0</version>
                <scope>compile</scope>
            </dependency>

            <!-- Source: https://mvnrepository.com/artifact/com.h2database/h2 -->
            <dependency>
                <groupId>com.h2database</groupId>
                <artifactId>h2</artifactId>
<!--                <version>2.4.240</version>-->
                <scope>test</scope>
            </dependency>

            <!-- JWT -->
            <!-- Source: https://mvnrepository.com/artifact/io.jsonwebtoken/jjwt-api -->
            <dependency>
                <groupId>io.jsonwebtoken</groupId>
                <artifactId>jjwt-api</artifactId>
                <version>0.13.0</version>
                <scope>compile</scope>
            </dependency>

            <!-- Source: https://mvnrepository.com/artifact/io.jsonwebtoken/jjwt-impl -->
            <dependency>
                <groupId>io.jsonwebtoken</groupId>
                <artifactId>jjwt-impl</artifactId>
                <version>0.13.0</version>
                <scope>runtime</scope>
            </dependency>

            <!-- Source: https://mvnrepository.com/artifact/io.jsonwebtoken/jjwt-jackson -->
            <dependency>
                <groupId>io.jsonwebtoken</groupId>
                <artifactId>jjwt-jackson</artifactId>
                <version>0.13.0</version>
                <scope>runtime</scope>
            </dependency>

            <!-- Source: https://mvnrepository.com/artifact/org.apache.commons/commons-lang3 -->
            <dependency>
                <groupId>org.apache.commons</groupId>
                <artifactId>commons-lang3</artifactId>
                <version>3.20.0</version>
                <scope>compile</scope>
            </dependency>

            <!-- Source: https://mvnrepository.com/artifact/org.apache.commons/commons-collections4 -->
            <dependency>
                <groupId>org.apache.commons</groupId>
                <artifactId>commons-collections4</artifactId>
                <version>4.5.0</version>
                <scope>compile</scope>
            </dependency>

            <!-- Source: https://mvnrepository.com/artifact/org.apache.commons/commons-text -->
            <dependency>
                <groupId>org.apache.commons</groupId>
                <artifactId>commons-text</artifactId>
                <version>1.15.0</version>
                <scope>compile</scope>
            </dependency>

            <!-- Source: https://mvnrepository.com/artifact/org.apache.commons/commons-compress -->
            <dependency>
                <groupId>org.apache.commons</groupId>
                <artifactId>commons-compress</artifactId>
                <version>1.28.0</version>
                <scope>compile</scope>
            </dependency>

            <!-- Source: https://mvnrepository.com/artifact/org.apache.commons/commons-configuration2 -->
            <dependency>
                <groupId>org.apache.commons</groupId>
                <artifactId>commons-configuration2</artifactId>
                <version>2.14.0</version>
                <scope>compile</scope>
            </dependency>

            <!-- Source: https://mvnrepository.com/artifact/org.apache.commons/commons-dbcp2 -->
            <dependency>
                <groupId>org.apache.commons</groupId>
                <artifactId>commons-dbcp2</artifactId>
                <version>2.14.0</version>
                <scope>compile</scope>
            </dependency>

            <!-- Source: https://mvnrepository.com/artifact/org.apache.commons/commons-fileupload2-jakarta-servlet6 -->
            <dependency>
                <groupId>org.apache.commons</groupId>
                <artifactId>commons-fileupload2-jakarta-servlet6</artifactId>
                <version>2.0.0-M5</version>
                <scope>compile</scope>
            </dependency>

            <!-- Source: https://mvnrepository.com/artifact/com.alibaba.fastjson2/fastjson2 -->
            <dependency>
                <groupId>com.alibaba.fastjson2</groupId>
                <artifactId>fastjson2</artifactId>
                <version>2.0.61</version>
                <scope>compile</scope>
            </dependency>

            <!-- Source: https://mvnrepository.com/artifact/com.google.guava/guava -->
            <dependency>
                <groupId>com.google.guava</groupId>
                <artifactId>guava</artifactId>
                <version>33.6.0-jre</version>
                <scope>compile</scope>
            </dependency>

            <!-- Source: https://mvnrepository.com/artifact/cn.hutool/hutool-all -->
            <dependency>
                <groupId>cn.hutool</groupId>
                <artifactId>hutool-all</artifactId>
                <version>5.8.44</version>
                <scope>compile</scope>
            </dependency>

            <!-- Source: https://mvnrepository.com/artifact/com.github.ifeilong/feilong -->
            <dependency>
                <groupId>com.github.ifeilong</groupId>
                <artifactId>feilong</artifactId>
                <version>4.5.1</version>
                <scope>compile</scope>
            </dependency>

            <!-- Source: https://mvnrepository.com/artifact/com.xuxueli/xxl-tool -->
            <dependency>
                <groupId>com.xuxueli</groupId>
                <artifactId>xxl-tool</artifactId>
                <version>2.5.0</version>
                <scope>compile</scope>
            </dependency>

            <!-- https://mvnrepository.com/artifact/com.aliyun/aliyun-java-sdk-core -->
            <dependency>
                <groupId>com.aliyun</groupId>
                <artifactId>aliyun-java-sdk-core</artifactId>
                <version>4.5.18</version>
            </dependency>

            <!-- https://mvnrepository.com/artifact/com.aliyun/aliyun-java-sdk-ecs -->
            <dependency>
                <groupId>com.aliyun</groupId>
                <artifactId>aliyun-java-sdk-ecs</artifactId>
                <version>4.23.10</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-aop</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-devtools</artifactId>
            <scope>runtime</scope>
            <optional>true</optional>
        </dependency>

        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <optional>true</optional>
        </dependency>

        <dependency>
            <groupId>com.alibaba.fastjson2</groupId>
            <artifactId>fastjson2</artifactId>
        </dependency>

        <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
        </dependency>

        <dependency>
            <groupId>cn.hutool</groupId>
            <artifactId>hutool-all</artifactId>
        </dependency>

        <dependency>
            <groupId>com.github.ifeilong</groupId>
            <artifactId>feilong</artifactId>
        </dependency>

        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-lang3</artifactId>
        </dependency>

        <dependency>
            <groupId>com.xuxueli</groupId>
            <artifactId>xxl-tool</artifactId>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <!-- https://mvnrepository.com/artifact/org.apache.maven.plugins/maven-compiler-plugin -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.15.0</version>
                <configuration>
                    <source>${java.version}</source>
                    <target>${java.version}</target>
                </configuration>
            </plugin>

            <!-- https://mvnrepository.com/artifact/org.apache.maven.plugins/maven-surefire-plugin -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>3.5.5</version>
                <configuration>
                    <!-- Skipping Tests -->
                    <skipTests>true</skipTests>
                </configuration>
            </plugin>

            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <excludes>
                        <exclude>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                        </exclude>
                    </excludes>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>repackage</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>