<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <!-- https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-starter-parent -->
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.5.14</version>
    </parent>

    <groupId>io.github.jiangxingfeng</groupId>
    <artifactId>asura-boot</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <packaging>pom</packaging>

    <modules>
        <module>asura-activiti</module>
        <module>asura-actuator</module>
        <module>asura-admin-client</module>
        <module>asura-admin-server</module>
        <module>asura-akka</module>
        <module>asura-annotation</module>
        <module>asura-aop</module>
        <module>asura-arthas</module>
        <module>asura-async</module>
        <module>asura-auto-configuration</module>
        <module>asura-batch</module>
        <module>asura-bom</module>
        <module>asura-caffeine</module>
        <module>asura-camunda</module>
        <module>asura-cassandra</module>
        <module>asura-clickhouse</module>
        <module>asura-code-executor</module>
        <module>asura-common</module>
        <module>asura-completablefuture</module>
        <module>asura-configuration-processor</module>
        <module>asura-couchbase</module>
        <module>asura-custom-starter</module>
        <module>asura-custom-starter-test</module>
        <module>asura-ddd-structure</module>
        <module>asura-disruptor</module>
        <module>asura-doris</module>
        <module>asura-easyexcel</module>
        <module>asura-elasticsearch</module>
        <module>asura-example</module>
        <module>asura-fastexcel</module>
        <module>asura-flaw</module>
        <module>asura-flowable</module>
        <module>asura-graphql</module>
        <module>asura-graphql-java-kickstart</module>
        <module>asura-guava</module>
        <module>asura-hazelcast</module>
        <module>asura-httpcomponents</module>
        <module>asura-hutool</module>
        <module>asura-hystrix</module>
        <module>asura-i18n</module>
        <module>asura-influxdb</module>
        <module>asura-jackson</module>
        <module>asura-jdbc</module>
        <module>asura-jib</module>
        <module>asura-jkube</module>
        <module>asura-jooq</module>
        <module>asura-jpa</module>
        <module>asura-jwt</module>
        <module>asura-kafka</module>
        <module>asura-kafka-streams</module>
        <module>asura-knife4j</module>
        <module>asura-kubernetes</module>
        <module>asura-liteflow</module>
        <module>asura-lock4j-redisson</module>
        <module>asura-lock4j-zookeeper</module>
        <module>asura-log</module>
        <module>asura-logstash</module>
        <module>asura-modulith-structure</module>
        <module>asura-mongodb</module>
        <module>asura-multi-datasource-transaction</module>
        <module>asura-mybatis-plus</module>
        <module>asura-mybatis-plus-druid-dynamic-datasource</module>
        <module>asura-mybatis-plus-druid-multi-datasource</module>
        <module>asura-mybatis-plus-sharding-jdbc</module>
        <module>asura-neo4j</module>
        <module>asura-netty</module>
        <module>asura-netty-client</module>
        <module>asura-netty-common</module>
        <module>asura-netty-server</module>
        <module>asura-okhttp</module>
        <module>asura-poi</module>
        <module>asura-postgressql</module>
        <module>asura-prometheus</module>
        <module>asura-pulsar</module>
        <module>asura-quartz</module>
        <module>asura-questdb</module>
        <module>asura-r2dbc</module>
        <module>asura-rabbitmq</module>
        <module>asura-rabbitmq-consumer</module>
        <module>asura-rabbitmq-producer</module>
        <module>asura-rate-limit</module>
        <module>asura-redis</module>
        <module>asura-redis-jedis</module>
        <module>asura-redis-reactive</module>
        <module>asura-redisson</module>
        <module>asura-redisson-client</module>
        <module>asura-redisson-interface</module>
        <module>asura-redisson-server</module>
        <module>asura-resilience4j</module>
        <module>asura-rest-template</module>
        <module>asura-rocketmq</module>
        <module>asura-screw</module>
        <module>asura-security</module>
        <module>asura-sentinel</module>
        <module>asura-shardingsphere</module>
        <module>asura-shardingsphere-jdbc</module>
        <module>asura-skywalking</module>
        <module>asura-sse</module>
        <module>asura-ssl</module>
        <module>asura-temporal</module>
        <module>asura-test</module>
        <module>asura-thrift</module>
        <module>asura-tomcat</module>
        <module>asura-tree</module>
        <module>asura-undertow</module>
        <module>asura-validation</module>
        <module>asura-webflux</module>
        <module>asura-xxl-job</module>
    </modules>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <java.version>25</java.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.asura.bom</groupId>
                <artifactId>asura-bom</artifactId>
                <version>${project.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-aop</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-devtools</artifactId>
            <scope>runtime</scope>
            <optional>true</optional>
        </dependency>

        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <optional>true</optional>
        </dependency>

        <dependency>
            <groupId>com.alibaba.fastjson2</groupId>
            <artifactId>fastjson2</artifactId>
        </dependency>

        <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
        </dependency>

        <dependency>
            <groupId>cn.hutool</groupId>
            <artifactId>hutool-all</artifactId>
        </dependency>

        <dependency>
            <groupId>com.github.ifeilong</groupId>
            <artifactId>feilong</artifactId>
        </dependency>

        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-lang3</artifactId>
        </dependency>

        <dependency>
            <groupId>com.xuxueli</groupId>
            <artifactId>xxl-tool</artifactId>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <!-- https://mvnrepository.com/artifact/org.apache.maven.plugins/maven-compiler-plugin -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.15.0</version>
                <configuration>
                    <source>${java.version}</source>
                    <target>${java.version}</target>
                </configuration>
            </plugin>

            <!-- https://mvnrepository.com/artifact/org.apache.maven.plugins/maven-surefire-plugin -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>3.5.5</version>
                <configuration>
                    <!-- Skipping Tests -->
                    <skipTests>true</skipTests>
                </configuration>
            </plugin>

            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <excludes>
                        <exclude>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                        </exclude>
                    </excludes>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>repackage</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>