spring:
  datasource:
    url: jdbc:h2:file:./data/testdb;DB_CLOSE_DELAY=-1;MODE=MYSQL;DATABASE_TO_UPPER=false
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true  # 启用H2控制台便于调试
      # 控制台路径 http://localhost:8080/h2-console
      path: /h2-console

logging:
  level:
    com.spring.boot.security: DEBUG # 开发时打印更详细的日志
