<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>io.github.jiangxingfeng</groupId>
		<artifactId>asura-boot</artifactId>
		<version>1.0.0-SNAPSHOT</version>
	</parent>

	<artifactId>${project.artifact.name}-jib</artifactId>

	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>com.google.cloud.tools</groupId>
				<artifactId>jib-maven-plugin</artifactId>
				<version>3.3.1</version>
				<configuration>
					<from>
						<!-- 基础镜像 -->
						<image>eclipse-temurin:17.0.6_10-jre-focal</image>
					</from>
					<to>
						<!-- 镜像名称和tag -->
						<image>rock-boot/spring-boot-jib:${project.version}</image>
					</to>
					<!-- 镜像文件名称 -->
					<outputPaths>
						<tar>target/${project.artifactId}.tar</tar>
						<digest>target/${project.artifactId}.digest</digest>
						<imageId>target/${project.artifactId}.id</imageId>
						<imageJson>target/${project.artifactId}.json</imageJson>
					</outputPaths>
				</configuration>
				<executions>
					<execution>
						<!-- 编译阶段 -->
						<phase>compile</phase>
						<goals>
							<!-- 构建镜像文件 -->
							<goal>buildTar</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>

</project>
