<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>io.github.limengcanyu</groupId>
        <artifactId>limengcanyu-boot</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>

    <artifactId>limengcanyu-arthas</artifactId>
    <name>limengcanyu-arthas</name>
    <description>limengcanyu-arthas</description>

    <dependencies>
        <dependency>
            <groupId>com.taobao.arthas</groupId>
            <artifactId>arthas-spring-boot-starter</artifactId>
            <version>3.6.1</version>
            <scope>runtime</scope>
        </dependency>
    </dependencies>

</project>
