<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<artifactId>rock-boot</artifactId>
		<groupId>org.rock.boot</groupId>
		<version>1.0-SNAPSHOT</version>
	</parent>

	<groupId>com.spring.boot.temporal</groupId>
	<artifactId>spring-boot-temporal</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>spring-boot-temporal</name>
	<description>spring-boot-temporal</description>

	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-jdbc</artifactId>
		</dependency>

		<!-- MyBatis Plus -->
		<dependency>
			<groupId>com.baomidou</groupId>
			<artifactId>mybatis-plus-boot-starter</artifactId>
			<version>3.5.14</version>
		</dependency>

		<!-- H2 Database (开发测试) -->
		<dependency>
			<groupId>com.h2database</groupId>
			<artifactId>h2</artifactId>
			<scope>runtime</scope>
		</dependency>

		<!-- MySQL Driver (生产) -->
		<!-- https://mvnrepository.com/artifact/com.mysql/mysql-connector-j -->
		<dependency>
			<groupId>com.mysql</groupId>
			<artifactId>mysql-connector-j</artifactId>
			<version>9.4.0</version>
		</dependency>

		<!-- Temporal SDK -->
		<dependency>
			<groupId>io.temporal</groupId>
			<artifactId>temporal-sdk</artifactId>
			<version>1.17.0</version>
		</dependency>
	</dependencies>

</project>
