GET http://localhost:8080/api/test/user
Accept: */*
Cache-Control: no-cache
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJqZXNzaWNhIiwiaWF0IjoxNzU4MTE2ODAwLCJleHAiOjE3NTgyMDMyMDB9.y-RKOhmKnDUp660T8zZtTA-QxFdm44TJjQPCiKIbYqh8xhk011ft5Go0WSuIs-jf5h7afcp7MIUZ2K8F1DL-kQ

########################################################################################################################
### Send POST request with json body
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "username": "rock",
  "password": "1234567890"
}

### Send POST request with json body
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "username": "rock",
  "password": "1234567890"
}

########################################################################################################################
### GET request with a header
GET localhost:8080/security/auth/logout?username=rock
Accept: application/json

########################################################################################################################
### GET request with a header
GET localhost:8080/api/test/user
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJqZXNzaWNhIiwiaWF0IjoxNzU4MTE3MzA4LCJleHAiOjE3NTgyMDM3MDh9.imn-AOBxjHz7no-2Va14qg5E78OS9eytALsdcu6VWbifyiWyPYg8QfYJmR7-ThtBo9qWbpWYaeXchqs6kbBn9A

### GET request with a header
GET localhost:8080/api/test/admin
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJqZXNzaWNhIiwiaWF0IjoxNzU4MTE3MzA4LCJleHAiOjE3NTgyMDM3MDh9.imn-AOBxjHz7no-2Va14qg5E78OS9eytALsdcu6VWbifyiWyPYg8QfYJmR7-ThtBo9qWbpWYaeXchqs6kbBn9A

### GET request with a header
GET localhost:8080/api/test/public
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJqZXNzaWNhIiwiaWF0IjoxNzU4MTE3MzA4LCJleHAiOjE3NTgyMDM3MDh9.imn-AOBxjHz7no-2Va14qg5E78OS9eytALsdcu6VWbifyiWyPYg8QfYJmR7-ThtBo9qWbpWYaeXchqs6kbBn9A

########################################################################################################################
### Authorization by token, part 1. Retrieve and save token.
POST https://httpbin.org/post
Content-Type: application/json

{
  "token": "my-secret-token"
}

> {% client.global.set("auth_token", response.body.json.token); %}

### Authorization by token, part 2. Use token to authorize.
GET https://httpbin.org/headers
Authorization: Bearer {{auth_token}}

########################################################################################################################
