<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>io.github.limengcanyu</groupId>
        <artifactId>limengcanyu-boot</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>

    <artifactId>${project.artifact.name}-rocketmq-example</artifactId>
    <packaging>pom</packaging>

    <modules>
        <module>${project.artifact.name}-rocketmq-acl-consume</module>
        <module>${project.artifact.name}-rocketmq-acl-produce</module>
        <module>${project.artifact.name}-rocketmq-consume</module>
        <module>${project.artifact.name}-rocketmq-produce</module>
    </modules>

    <dependencies>
        <dependency>
            <groupId>org.apache.rocketmq</groupId>
            <artifactId>rocketmq-spring-boot-starter</artifactId>
            <version>2.2.1</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>

</project>
